import { downloadPlanAsPdf } from '../lib/printPlan'

const SOURCES =
  'O*NET task ratings · Anthropic Economic Index · Eloundou et al. (2023) task exposure'

export default function PlanPhases({ plan, occupationTitle }) {
  if (!plan) return null

  const current = plan.path?.find((n) => n.is_current)
  const destination = plan.path?.find((n) => !n.is_current)
  const title = occupationTitle || current?.title || 'Career plan'

  return (
    <section className="plan">
      {/* Print-only masthead. On screen the page header already says all of
          this; on paper the document has to introduce itself. */}
      <header className="plan__masthead" aria-hidden="true">
        <p className="plan__masthead-brand">Groundwork</p>
        <h1 className="plan__masthead-title">{title}</h1>
        <p className="plan__masthead-sub">
          Task-level AI exposure and a plan built from it.
          {' '}Generated {new Date().toLocaleDateString(undefined, {
            year: 'numeric', month: 'long', day: 'numeric',
          })}.
        </p>
      </header>

      <div className="plan__bar">
        <h3 className="plan__heading">Your plan</h3>
        <button
          type="button"
          className="plan__download"
          onClick={() => downloadPlanAsPdf(title)}
        >
          Save as PDF
        </button>
      </div>

      <p className="plan__summary">{plan.summary}</p>

      {plan.path?.length > 0 && (
        <ol className="plan__path">
          {plan.path.map((node) => (
            <li key={node.soc_code} className="plan__node">
              <span className="plan__score">{node.resilience_score}</span>
              <span className="plan__node-body">
                <span className="plan__node-title">
                  {node.title}
                  {node.is_current && <span className="plan__meta"> · where you are</span>}
                  {!node.is_current && (
                    <span className="plan__meta"> · {node.overlap_pct}% task overlap</span>
                  )}
                  {node.interest_fit != null && (
                    <span className="plan__meta"> · {node.interest_fit}% interest fit</span>
                  )}
                </span>
                {node.rationale && <span className="plan__rationale">{node.rationale}</span>}
              </span>
            </li>
          ))}
        </ol>
      )}

      {plan.phases?.map((phase) => (
        <div key={phase.window} className="plan__phase">
          <h4 className="plan__window">{phase.window}</h4>
          <ul className="plan__milestones">
            {phase.milestones?.map((m) => (
              <li key={m.action}>
                <p className="plan__action">{m.action}</p>
                <p className="plan__reason">{m.reason}</p>
                <p className="plan__source">{m.data_source}</p>
              </li>
            ))}
          </ul>
        </div>
      ))}

      <p className="plan__provenance">
        Every score and overlap figure here was computed from O*NET task
        ratings, Anthropic Economic Index labels and Eloundou et al. exposure
        betas. No number on this page was generated by a language model.
        {plan.generated_by === 'computation' && ' This plan was written without one too.'}
      </p>

      {/* Printed pages travel away from the app, so the sources have to
          travel with them. */}
      <footer className="plan__colophon" aria-hidden="true">
        <p>{SOURCES}</p>
        {destination && (
          <p>
            {current?.title} ({current?.resilience_score}) →{' '}
            {destination.title} ({destination.resilience_score}) ·{' '}
            {destination.overlap_pct}% task overlap
          </p>
        )}
      </footer>
    </section>
  )
}
