export default function PlanPhases({ plan }) {
  if (!plan) return null

  return (
    <section className="plan">
      <h3 className="plan__heading">Your plan</h3>
      <p className="plan__summary">{plan.summary}</p>

      {plan.path?.length > 0 && (
        <ol className="plan__path">
          {plan.path.map((node) => (
            <li key={node.soc_code} className="plan__node">
              <span className="plan__score">{node.resilience_score}</span>
              <span className="plan__node-body">
                <span className="plan__node-title">
                  {node.title}
                  {node.is_current && <span className="plan__meta"> · where you are</span>}
                  {!node.is_current && (
                    <span className="plan__meta"> · {node.overlap_pct}% task overlap</span>
                  )}
                </span>
                {node.rationale && <span className="plan__rationale">{node.rationale}</span>}
              </span>
            </li>
          ))}
        </ol>
      )}

      {plan.phases?.map((phase) => (
        <div key={phase.window} className="plan__phase">
          <h4 className="plan__window">{phase.window}</h4>
          <ul className="plan__milestones">
            {phase.milestones?.map((m) => (
              <li key={m.action}>
                <p className="plan__action">{m.action}</p>
                <p className="plan__reason">{m.reason}</p>
                <p className="plan__source">{m.data_source}</p>
              </li>
            ))}
          </ul>
        </div>
      ))}

      <p className="plan__provenance">
        Every score and overlap figure here was computed from O*NET task
        ratings, Anthropic Economic Index labels and Eloundou et al. exposure
        betas. No number on this page was generated by a language model.
        {plan.generated_by === 'computation' && ' This plan was written without one too.'}
      </p>
    </section>
  )
}
